name: "csteach125"
subname: "Visual Information Processing"
description: "a collection of resources for COMP 125..."

url: "http://localhost:4000"

paginate: 10

markdown: kramdown
permalink: "/:categories/:title"
highlighter: rouge

excerpt_separator: <!--more-->

collections:
  library:
    output: true
  indices:
    output: true

gems:
  - jekyll-sitemap
